#pragma once
#include <shtypes.h>

constexpr COMDLG_FILTERSPEC filterSpecs[] =
{
	{L"Wavefront object file",L"*.obj"},
	{L"Collada", L"*.dae, *.xml"},
	{L"Blender", L"*.blend"},
	{L"Biovision BVH", L"*.bvh"},
	{L"3D Studio Max 3DS", L"*.3ds"},
	{L"3D Studio Max ASE", L"*.ase"},
	{L"Stanford Polygon Library", L"*.ply"},
	{L"AutoCAD DXF", L"*.dxf"},
	{L"IFC - STEP", L"*.ifc"},
	{L"Neutral File Format", L"*.nff"},
	{L"Sense8 WorldToolkit", L"*.nff"},
	{L"Valve Model", L"*.smd, *.vta"},
	{L"Quake I", L"*.mdl"},
	{L"Quake II", L"*.md2"},
	{L"Quake III", L"*.md3"},
	{L"Quake 3 BSP", L"*.pk3"},
	{L"RtCW", L"*.mdc"},
	{L"Doom 3 ", L"*.md5mesh, *.md5anim, *.md5camera"},
	{L"DirectX X", L"*.x"},
	{L"Quick3D", L"*.q3o, *.q3s"},
	{L"Raw Triangles", L"*.raw"},
	{L"AC3D", L"*.ac"},
	{L"Stereolithography", L"*.stl"},
	{L"Autodesk DXF", L"*.dxf"},
	{L"Irrlicht Mesh", L"*.irrmesh, *.xml"},
	{L"Irrlicht Scene", L"*.irr, *.xml"},
	{L"Object File Format", L"*.off"},
	{L"Terragen Terrain", L"*.ter"},
	{L"3D GameStudio Model", L"*.mdl"},
	{L"3D GameStudio Terrain", L"*.hmp"},
	{L"Ogre", L"*.mesh*.xml, *.skeleton*.xml, *.material"},
	{L"Milkshape 3D", L"*.ms3d"},
	{L"LightWave Model", L"*.lwo"},
	{L"LightWave Scene", L"*.lws"},
	{L"Modo Model", L"*.lxo"},
	{L"CharacterStudio Motion", L"*.csm"},
	{L"Stanford Ply", L"*.ply"},
	{L"TrueSpace", L"*.cob, *.scn"},
	{L"All Files", L"*.*"}
};